--- #YAML:1.0
name:               CGI.pm
version:            3.51
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    FCGI:        0.67
    File::Spec:  0.82
    perl:        5.006000
    Test::More:  0.8
resources:
    repository:  http://github.com/markstos/CGI.pm/tree/master
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
