--- #YAML:1.0
name:                CGI.pm
version:             3.49
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    FCGI:                          0.67
    File::Spec:                    0.82
    Test::More:                    0.8
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
